pull_request_rules:
  - name: Automatic squash on approval
    conditions:
      - approved-reviews-by>=1
      - author=dependabot
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: squash
