version: '2.1'

services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      - NODE_ENV=serverest-test
    volumes:
      - ./test:/app/test

  test:
    extends: base
    environment: 
      - CI
    command: npm run test
    volumes:
      - ./coverage:/app/coverage

  test-contract:
    extends: base
    environment:
      - CONSUMER_VERSION_TAG
      - PACT_BROKER_TOKEN
      - GITHUB_BRANCH
      - PACT_URL
      - TRIGGERED_BY_PACT_CHANGE
      - PACT_BROKER_BASE_URL
      - CI
    command: npm run test:contract

  test-mutation:
    extends: base
    environment:
      - STRYKER_DASHBOARD_API_KEY
    command: npm run test:mutation

  test-mutation-diff:
    extends: base
    environment:
      - STRYKER_DASHBOARD_API_KEY
    command: npm run test:mutation:diff
