version: '3.8'

services:
  base:
    build:
      context: .
      target: test
    volumes:
      - ./test:/app/test

  run-dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  test-contract:
    extends: base
    environment:
      - PACT_BROKER_TOKEN
      - PACT_URL
      - CI
    command: npm run test:contract
    volumes:
      - ./.git:/app/.git

  test:
    extends: base
    command: npm test
    volumes:
      - ./coverage:/app/coverage

  test-unit:
    extends: base
    command: npm run test:unit
    volumes:
      - ./coverage:/app/coverage

  test-mutation:
    extends: base
    environment:
      - STRYKER_DASHBOARD_API_KEY
    command: npm run test:mutation
    volumes:
      - ./reports:/app/reports

  test-mutation-diff:
    extends: base
    environment:
      - STRYKER_DASHBOARD_API_KEY
    command: npm run test:mutation:diff
    volumes:
      - ./reports:/app/reports
