name: Teste Repository Dispatch
on:
  repository_dispatch:
    types: [consumer-dispatch]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload }}
      - run: echo ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.branch }}
