name: Continuous Delivery

on:
  push:
    branches: [trunk, beta]

jobs:
  common-ci:
    uses: ./.github/workflows/common_ci.yml
    secrets: inherit
    with:
      type_pipeline: 'continuous_delivery'

  test-mutation:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v32
      with:
        files: src
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        STRYKER_DASHBOARD_API_KEY: op://serverest-ci-cd/stryker-mutator/api_key
    - name: Run mutation test
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: make test-mutation
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ env.STRYKER_DASHBOARD_API_KEY }}

  release:
    needs: [common-ci]

    concurrency: create_release

    runs-on: ubuntu-22.04
    environment: production

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Node.js Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        NPM_TOKEN: op://serverest-ci-cd/npm/npm_token
        DOCKER_REGISTRY_USER: op://serverest-ci-cd/docker/username
        DOCKER_REGISTRY_PASSWORD: op://serverest-ci-cd/docker/password
        PACT_BROKER_TOKEN: op://serverest-ci-cd/pactflow/pact_broker_token
    - name: Release on NPM and Docker
      run: npx semantic-release@18.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ env.NPM_TOKEN }}
        DOCKER_REGISTRY_USER: ${{ env.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ env.DOCKER_REGISTRY_PASSWORD }}
    - run: docker-compose build test-contract
    - name: Run contract test
      run: make test-contract
      env:
        PACT_BROKER_TOKEN: ${{ env.PACT_BROKER_TOKEN }}
