name: Continuous Integration

on:
  pull_request:
    branches-ignore:
      - beta
  workflow_dispatch:

jobs:
  # common-ci:
  #   uses: ./.github/workflows/common_ci.yml
  #   secrets: inherit
  #   with:
  #     type_pipeline: 'continuous_integration'

  cancel-previous-run:

    runs-on: ubuntu-22.04

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

  test-mutation-diff:

    runs-on: ubuntu-22.04

    steps:
    - name: Generate and fill .env file with secrets
      run: |
        # Install 1password CLI
        curl https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip > op.zip
        unzip op.zip
        sudo mv op /usr/local/bin
        rm op.zip
        # Generate .env file
        # Append secret MOESIF_APPLICATION_ID
        op read op://serverest-ci-cd/moesif/application_id | sed 's/^/MOESIF_APPLICATION_ID=/' >> .env
        cat .env
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
