name: Continuous Integration

on:
  push:
    branches-ignore:
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup 
      uses: actions/setup-node@v2.0.0
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  commit-lint:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v1
      with:
        helpURL: https://github.com/PauloGoncalvesBH/ServeRest/blob/master/CONTRIBUTING.md

  test-api:

    runs-on: ubuntu-latest

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup 
      uses: actions/setup-node@v2.0.0
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: API Test
      run: npm test
    - name: Update Codecov Report
      uses: codecov/codecov-action@v1
