name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2.1.4
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  commit-lint:

    runs-on: ubuntu-18.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v2.1.6
      with:
        helpURL: https://github.com/ServeRest/ServeRest/blob/trunk/.github/CONTRIBUTING.md

  dockerfile-lint:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - run: docker run --rm -i hadolint/hadolint < Dockerfile

  test-api:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js v${{ matrix.node }} Setup
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node }}
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: API Test
      run: npm test

  test-mutation-diff:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2.1.4
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Mutation Test - Changed files in the branch
      run: |
        git fetch origin trunk:refs/remotes/origin/trunk
        npm run test:mutation:diff
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  test-infra-docker:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3' 
    - name: Install dependencies
      run: cd test/infra && go mod tidy
    - name: Run infra test
      run: cd test/infra && go test -v -timeout 10m
