name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2.1.0
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  commit-lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v1
      with:
        helpURL: https://github.com/PauloGoncalvesBH/ServeRest/blob/master/.github/CONTRIBUTING.md

  test-api:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js v${{ matrix.node }} Setup
      uses: actions/setup-node@v2.1.0
      with:
        node-version: ${{ matrix.node }}
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: API Test
      run: npm test
    - name: Update Codecov Report
      uses: codecov/codecov-action@v1.0.7
