name: Deploy on serverest.dev

on:
  release:
    types: [released]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  deploy-on-serverest-dev:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup SSH to use on 'git push umbler'
      uses: shimataro/ssh-key-action@v2.2.0
      with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        public-key:  ${{ secrets.SSH_PUBLIC_KEY }}
        known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - if: github.event_name == 'release'
      name: Deploy new release on serverest.dev
      run: |
        git remote add umbler ssh://git@geonosis.deploy.umbler.com:9922/jnydrgre/serverest-dev.git
        git fetch --unshallow origin
        git push umbler ${GITHUB_REF##*/}:trunk --no-verify --force
    - if: github.event_name != 'release'
      name: Daily clean - serverest.dev database
      run: |
        git remote add umbler ssh://git@geonosis.deploy.umbler.com:9922/jnydrgre/serverest-dev.git
        git fetch --unshallow origin
        git config --global user.email "deployumbler@github.com"
        git config --global user.name "deploy umbler"
        git commit --allow-empty -m "empty commity" --no-verify
        git push umbler ${GITHUB_REF##*/}:trunk --no-verify --force
