name: Deploy on api.serverest.dev

on:
  schedule:
    - cron: "0 07 * * *"
  push:
    branches: api-online
  workflow_dispatch:

jobs:
  deploy-doc:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2.1.1
    - name: Installation of Node.js dependencies
      run: npm ci --production
    - name: Conf SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: geonosis.deploy.umbler.com
    - name: Release on api.serverest.dev
      run: |
        git remote add umbler ssh://git@geonosis.deploy.umbler.com:9922/jnydrgre/api-serverest-dev.git
        git push umbler master --force --no-verify
