name: Deploy on api.serverest.dev

on:
  schedule:
    - cron: "0 07 * * *"
  push:
    branches: api-online
  workflow_dispatch:

jobs:
  deploy-doc:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Conf SSH
      uses: shimataro/ssh-key-action@v1.5.0
      with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        public-key:  ${{ secrets.SSH_PUBLIC_KEY }}
        known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - name: Release on api.serverest.dev
      run: |
        git remote add umbler ssh://git@geonosis.deploy.umbler.com:9922/jnydrgre/api-serverest-dev.git
        git push umbler api-online:master --force --no-verify
